# Generated by Django 3.1 on 2020-02-15 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(verbose_name='record_time')),
                ('user_name', models.CharField(max_length=200)),
                ('user_code', models.CharField(max_length=200)),
                ('user_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=200)),
                ('is_ok', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.UsersSht')),
            ],
        ),
    ]
