# Generated by Django 3.1 on 2020-02-21 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='definition_bt_fail_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_fail', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_蓝牙fail列表',
            },
        ),
        migrations.CreateModel(
            name='definition_bt_ver_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_ver', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_蓝牙驱动版本列表',
            },
        ),
        migrations.CreateModel(
            name='definition_env_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_测试场景列表',
            },
        ),
        migrations.CreateModel(
            name='definition_pc_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_type', models.CharField(max_length=200)),
                ('sys_ver', models.CharField(max_length=200)),
                ('bt_ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_bt_ver_table')),
            ],
            options={
                'verbose_name_plural': '定义_PC机型列表',
            },
        ),
        migrations.CreateModel(
            name='definition_phone_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=200)),
                ('wifi_chip_type', models.CharField(max_length=200)),
                ('sys_ver', models.CharField(max_length=200)),
                ('hwshare_ver', models.CharField(max_length=200)),
                ('more_info', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_Phone机型列表',
            },
        ),
        migrations.CreateModel(
            name='definition_wifi_fail_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_fail', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_wifi Fail列表',
            },
        ),
        migrations.CreateModel(
            name='definition_wifi_ver_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi_ver', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': '定义_wifi驱动版本列表',
            },
        ),
        migrations.CreateModel(
            name='test_id_belong_table',
            fields=[
                ('test_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(auto_now=True, verbose_name='record_time')),
                ('test_des', models.CharField(max_length=1000, unique=True)),
                ('more_info', models.CharField(max_length=1000)),
                ('chose_log_table', models.CharField(choices=[('wifi_pic_trans_log', 'wifi_pic_trans_log'), ('bt_rfcomm_log', 'bt_rfcomm_log')], default=1, max_length=50, verbose_name='选择对应的日志表')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_env_table')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_pc_table')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_phone_table')),
            ],
            options={
                'verbose_name_plural': '创建_测试任务ID列表',
            },
        ),
        migrations.CreateModel(
            name='test_softap_trans_run_log_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_No', models.IntegerField()),
                ('bt_socket_cnn', models.IntegerField()),
                ('bt_socket_trans', models.IntegerField()),
                ('create_softap', models.IntegerField()),
                ('connect_sofap', models.IntegerField()),
                ('tcp_udp_connect', models.IntegerField()),
                ('tcp_udp_speed', models.IntegerField()),
                ('destroy_softap', models.IntegerField()),
                ('result', models.CharField(max_length=4)),
                ('remark_info', models.CharField(blank=True, max_length=512, null=True)),
                ('bt_fail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_bt_fail_table')),
                ('test_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.test_id_belong_table')),
                ('wifi_fail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_wifi_fail_table')),
            ],
            options={
                'verbose_name_plural': '日志_softap传输细表',
            },
        ),
        migrations.CreateModel(
            name='test_bt_rfcomm_run_log_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_No', models.IntegerField()),
                ('socket_cnn', models.IntegerField()),
                ('socket_trans', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('remark_info', models.CharField(max_length=512)),
                ('bt_fail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_bt_fail_table')),
                ('test_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.test_id_belong_table')),
            ],
            options={
                'verbose_name_plural': '日志_蓝牙rfcomm测试记录细表',
            },
        ),
        migrations.CreateModel(
            name='report_record_by_test_tool_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_time', models.DateTimeField(default=datetime.datetime(2020, 2, 21, 8, 8, 13, 271157, tzinfo=utc))),
                ('run_count', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('fail_count', models.IntegerField()),
                ('pass_yield', models.FloatField()),
                ('test_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.test_id_belong_table')),
            ],
            options={
                'verbose_name_plural': 'Report_测试工具上报结果列表',
            },
        ),
        migrations.CreateModel(
            name='report_env_yield_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField()),
                ('total_run_count', models.IntegerField()),
                ('total_run_time', models.IntegerField(default=0)),
                ('total_run_fail_count', models.IntegerField()),
                ('total_pass_yield', models.FloatField()),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_env_table')),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_pc_table')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_phone_table')),
            ],
            options={
                'verbose_name_plural': '测试场景成功率报告',
            },
        ),
        migrations.AddField(
            model_name='definition_pc_table',
            name='wifi_ver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.definition_wifi_ver_table'),
        ),
    ]
