# Generated by Django 3.1 on 2020-02-15 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsersSht',
            new_name='UserSht',
        ),
    ]
