# Generated by Django 3.1 on 2020-02-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0002_auto_20200219_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_test_by_test_tool_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_count', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('fail_count', models.IntegerField()),
                ('pass_yield', models.FloatField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neartrans.test_id_belong_table')),
            ],
            options={
                'verbose_name_plural': '测试场景详细测试记录列表',
            },
        ),
        migrations.DeleteModel(
            name='report_test_detail_table',
        ),
    ]
