# Generated by Django 3.1 on 2020-02-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0002_auto_20200215_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersht',
            options={'managed': True},
        ),
    ]
