# Generated by Django 3.1 on 2020-02-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0003_auto_20200215_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersht',
            options={},
        ),
        migrations.RenameField(
            model_name='usersht',
            old_name='user_code',
            new_name='user_id',
        ),
    ]
