# Generated by Django 3.1 on 2020-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0004_report_env_yield_table_total_run_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='report_test_by_test_tool_table',
            new_name='report_record_by_test_tool_table',
        ),
        migrations.AlterModelOptions(
            name='report_record_by_test_tool_table',
            options={'verbose_name_plural': 'Report_测试工具上报结果列表'},
        ),
    ]
