# Generated by Django 3.1 on 2020-02-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0004_auto_20200215_0854'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='UserSht',
        ),
    ]
