# Generated by Django 3.1 on 2020-02-19 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0005_auto_20200219_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_record_by_test_tool_table',
            name='detail_record_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 16, 33, 59, 336351, tzinfo=utc)),
        ),
    ]
