# Generated by Django 3.1 on 2020-02-19 16:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('neartrans', '0006_report_record_by_test_tool_table_detail_record_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_record_by_test_tool_table',
            name='detail_record_time',
        ),
        migrations.AddField(
            model_name='report_record_by_test_tool_table',
            name='record_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 19, 16, 34, 34, 637580, tzinfo=utc)),
        ),
    ]
