# Generated by Django 3.1 on 2020-02-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uservote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='poker_log_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='poker_report_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200)),
                ('wang', models.IntegerField(default=0)),
                ('two', models.IntegerField(default=0)),
                ('one', models.IntegerField(default=0)),
                ('king', models.IntegerField(default=0)),
                ('queen', models.IntegerField(default=0)),
                ('jack', models.IntegerField(default=0)),
                ('ten', models.IntegerField(default=0)),
                ('nine', models.IntegerField(default=0)),
                ('eight', models.IntegerField(default=0)),
                ('seven', models.IntegerField(default=0)),
                ('six', models.IntegerField(default=0)),
                ('five', models.IntegerField(default=0)),
                ('four', models.IntegerField(default=0)),
                ('three', models.IntegerField(default=0)),
            ],
        ),
    ]
